import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Recoil from '../components/Recoil'
import AppBar from '../components/AppBar'
import ReactQuery from '@/components/ReactQuery'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VividReview',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Recoil>
          <ReactQuery>
          <div className='h-screen flex flex-col'>
            <AppBar />
            <div className='flex-1 overflow-auto'>
              {children}
            </div>
          </div>
          </ReactQuery>
        </Recoil>
      </body>
    </html>
  )
}
